# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28e92a29d79da14169fca5732f3f26bac27d988c20e18a1dfb548288c40215def92d736b18d71d231632d47197a158fb1f9cd0e49b8f03bcf9722cc076b4a485

test:
  secret_key_base: 9de07aa89c4a1064da705f1f4b9fe02f9cbea5de6d27c79a2b82f5a6d9db9a3b6a41b3e177a6532aba01fdb3911399a66011eaf60380c710039004292980de59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
